// templates/integrate-existing/react/ui/TernentPanel.tsx
import { useTernent } from "../useTernent";

export function TernentPanel() {
  const api = useTernent();

  if (!api) {
    return <p>Booting Ternent integration...</p>;
  }

  return (
    <section>
      <h2>Ternent integration panel</h2>
      <pre>{JSON.stringify(api.identity.getActiveIdentity(), null, 2)}</pre>
      <pre>{JSON.stringify(api.permissions.readableForViewer(), null, 2)}</pre>
      <pre>{JSON.stringify(api.tasks.visible(), null, 2)}</pre>
    </section>
  );
}

// templates/integrate-existing/svelte/ui/TernentPanel.svelte
<script lang="ts">
  import { useTernent } from "../useTernent";

  const api = useTernent();
</script>

<section>
  <h2>Ternent integration panel</h2>
  <pre>{JSON.stringify(api.identity.getActiveIdentity(), null, 2)}</pre>
  <pre>{JSON.stringify(api.permissions.readableForViewer(), null, 2)}</pre>
  <pre>{JSON.stringify(api.tasks.visible(), null, 2)}</pre>
</section>
