// templates/integrate-existing/svelte/ui/TernentPanel.svelte
<script lang="ts">
  import { useTernent } from "../useTernent";

  const api = useTernent();
</script>

<section>
  <h2>Ternent integration panel</h2>
  <pre>{JSON.stringify(api.identity.getActiveIdentity(), null, 2)}</pre>
  <pre>{JSON.stringify(api.permissions.readableForViewer(), null, 2)}</pre>
  <pre>{JSON.stringify(api.tasks.visible(), null, 2)}</pre>
</section>

// templates/integrate-existing/vue/ui/TernentPanel.vue
<script setup lang="ts">
import { useTernent } from "../useTernent";

const api = useTernent();
</script>

<template>
  <section>
    <h2>Ternent integration panel</h2>
    <pre>{{ JSON.stringify(api.value?.identity.getActiveIdentity(), null, 2) }}</pre>
    <pre>{{ JSON.stringify(api.value?.permissions.readableForViewer(), null, 2) }}</pre>
    <pre>{{ JSON.stringify(api.value?.tasks.visible(), null, 2) }}</pre>
  </section>
</template>
